## Airbnb DC Hosting Helper ##

## 1_data_collection ##

### Executive Summary ###

Airbnb was started in 2007 and has been disrupting the hospitality industry ever since. Hosts on Airbnb offer unique stays and local experiences for travelers that can't be replicated by a stay in a hotel. According to [their site,](https://news.airbnb.com/about-us/) Airbnb has helped over 4 million hosts welcome over 900 million guests in almost every country around the world. 

According to [SmartAsset's](https://smartasset.com/mortgage/where-do-airbnb-hosts-make-the-most-money) 2020 study on the profit potential of rentals in 15 of the largest Airbnb markets in the US, renting out an entire place or room can be a profitable venture. The average expected annual profit of Airbnb hosts renting out a full two bedroom apartment or house after expenses is $20,619 in the cities studied. For hosts renting out a one room in a two-bedroom home on Airbnb in these cities, they could expect to pay about 81% of their rent from renting on average. 

As you could imagine, there is a robust amount of Airbnb information in every major city around the world. To explore this data, [Inside Airbnb](http://insideairbnb.com/index.html) created an independent, non-commercial website that scrapes publicly available listing and review data from Airbnb every month and allows anyone to explore or work with this information.

This information can useful to many parties working with Airbnb. For this project, I will aim to use this information to help hosts understand what makes and Airbnb listing the most popular and what they could focus on to make their listing more competitive and increase their profits. I will specifically be focusing on Washington DC as my case study. I will also use the [Foursquare API](https://developer.foursquare.com/) to gather information on type of venues in each neighborhood to get a better idea of the city from a tourist's point of view and see if this impacts the Airbnb listing popularity.

### Problem Statement ###

I will create the best binary clasfication model to predict whether or not an Airbnb listing in DC will be considered popular or not compared to the current listing competition. In addition to the best predictive model, I will create a highly interpretive model to help hosts understand what features they could improve on their listing to increase popularity. These models will be deployed together an app that hosts can use to make their listings as strong as possible.

There are a few important metrics to point out for this project. The first is how to determine the binary classification of the listing being popular or not. I will use a combination of the number of ratings and the average rating to calculate popularity. Listings with over 60 reviews and over a 4.8 (out of 5) overall rating will be considered popular. I want to explore the features that separate this group from the rest. Why are these lisitngs getting such high ratings and reviews? Second, the model I select should have as consistent accuracy scores as possible between training and testing groups and ideally the scores for both groups should be high to explain as much variance as possible. I will also focus on optimizing the precision score (true positives over all predicted positives), because in this specific case it would be worse to tell a host that their listing will be popular if it is actually not.

Import libraries and read in data

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json, requests

In [ ]:
np.random.seed(100)

In [2]:
pd.set_option('display.max_columns', 300)

In [3]:
pd.set_option('display.max_rows', 300)

In [4]:
listings = pd.read_csv('../data/listings.csv.gz')

In [45]:
listings.head()

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,3686,https://www.airbnb.com/rooms/3686,20210710190002,2021-07-11,Vita's Hideaway,IMPORTANT NOTES<br />* Carefully read and be s...,We love that our neighborhood is up and coming...,https://a0.muscache.com/pictures/61e02c7e-3d66...,4645,https://www.airbnb.com/users/show/4645,Vita,2008-11-26,"Washington D.C., District of Columbia, United ...","I am a literary scholar, teacher, poet, vegan ...",within a day,80%,75%,f,https://a0.muscache.com/im/users/4645/profile_...,https://a0.muscache.com/im/users/4645/profile_...,Anacostia,2.0,2.0,"['email', 'phone', 'reviews', 'jumio', 'offlin...",t,t,"Washington, District of Columbia, United States",Historic Anacostia,NaN,38.86339,-76.98889,Private room in house,Private room,1,NaN,1 private bath,1.0,1.0,"[""First aid kit"", ""Long term stays allowed"", ""...",$55.00,2,365,2,2,365,365,2.0,365.0,NaN,t,1,31,61,336,2021-07-11,75,3,0,2014-06-22,2021-01-12,4.59,4.71,4.44,4.89,4.82,3.80,4.58,NaN,f,2,0,2,0,0.87
1,3943,https://www.airbnb.com/rooms/3943,20210710190002,2021-07-11,Historic Rowhouse Near Monuments,Please contact us before booking to make sure ...,This rowhouse is centrally located in the hear...,https://a0.muscache.com/pictures/432713/fab7dd...,5059,https://www.airbnb.com/users/show/5059,Vasa,2008-12-12,"Washington, District of Columbia, United States",I have been living and working in DC for the l...,within a few hours,100%,29%,f,https://a0.muscache.com/im/pictures/user/8ec69...,https://a0.muscache.com/im/pictures/user/8ec69...,Eckington,0.0,0.0,"['email', 'phone', 'reviews', 'kba']",t,t,"Washington, District of Columbia, United States","Edgewood, Bloomingdale, Truxton Circle, Eckington",NaN,38.91195,-77.00456,Private room in townhouse,Private room,2,NaN,1.5 shared baths,1.0,1.0,"[""Cooking basics"", ""First aid kit"", ""Dedicated...",$70.00,2,1125,2,2,1125,1125,2.0,1125.0,NaN,t,9,39,69,344,2021-07-11,429,0,0,2010-08-08,2018-08-07,4.82,4.89,4.91,4.94,4.90,4.54,4.74,NaN,f,2,0,2,0,3.22
2,4529,https://www.airbnb.com/rooms/4529,20210710190002,2021-07-11,Bertina's House Part One,This is large private bedroom with plenty of...,Very quiet neighborhood and it is easy accessi...,https://a0.muscache.com/pictures/86072003/6709...,5803,https://www.airbnb.com/users/show/5803,Bertina'S House,2008-12-30,"Washington, District of Columbia, United States","I am an easy going, laid back person who loves...",NaN,NaN,NaN,f,https://a0.muscache.com/im/users/5803/profile_...,https://a0.muscache.com/im/users/5803/profile_...,Eastland Gardens,3.0,3.0,"['email', 'phone', 'facebook', 'reviews', 'jum...",t,t,"Washington, District of Columbia, United States","Eastland Gardens, Kenilworth",NaN,38.90585,-76.94469,Private room in house,Private room,4,NaN,1 shared bath,1.0,1.0,"[""Cooking basics"", ""First aid kit"", ""Keypad"", ...",$54.00,30,180,30,30,180,180,30.0,180.0,NaN,t,29,59,89,179,2021-07-11,102,0,0,2014-09-23,2019-07-05,4.66,4.80,4.60,4.93,4.93,4.51,4.83,NaN,f,1,0,1,0,1.23
3,4967,https://www.airbnb.com/rooms/4967,20210710190002,2021-07-11,"DC, Near Metro","<b>The space</b><br />Hello, my name is Seveer...",NaN,https://a0.muscache.com/pictures/2439810/bb320...,7086,https://www.airbnb.com/users/show/7086,Seveer,2009-01-26,"Washington D.C., District of Columbia, United ...","I am fun, honest and very easy going and trave...",within a few hours,100%,78%,t,https://a0.muscache.com/im/pictures/user/6efb4...,https://a0.muscache.com/im/pictures/user/6efb4...,Ivy City,5.0,5.0,"['email', 'phone', 'reviews', 'kba']",t,t,NaN,"Ivy City, Arboretum, Trinidad, Carver Langston",NaN,38.91217,-76.99249,Private room in house,Private room,1,NaN,3 baths,1.0,1.0,"[""Cable TV"", ""TV with standard cable"", ""Kitche...",$99.00,2,365,2,2,365,365,2.0,365.0,NaN,t,0,0,0,146,2021-07-11,31,0,0,2012-02-13,2016-09-22,4.74,4.68,4.89,4.93,4.93,4.21,4.64,NaN,f,3,0,3,0,0.27
4,5589,https://www.airbnb.com/rooms/5589,20210710190002,2021-07-11,Cozy apt in Adams Morgan,This is a 1 br (bedroom + living room in Adams...,"Adams Morgan spills over with hipsters, salsa ...",https://a0.muscache.com/pictures/207249/9f1df8...,6527,https://www.airbnb.com/users/show/6527,Ami,2009-01-13,"Washington D.C., District of Columbia, United ...","I am an environmentalist, and I own and operat...",within a few hours,100%,17%,f,https://a0.muscache.com/im/users/6527/profile_...,https://a0.muscache.com/im/users/6527/profile_...,Adams Morgan,4.0,4.0,"['email', 'phone', 'facebook', 'reviews', 'jum...",t,t,"Washington, District of Columbia, United States","Kalorama Heights, Adams Morgan, Lanier Heights",NaN,38.91887,-77.04008,Entire apartment,Entire home/apt,3,NaN,1 bath,1.0,1.0,"[""Window guards"", ""Cooking basics"", ""First aid...",$86.00,5,150,5,23,150,150,8.8,150.0,NaN,t,7,32,62,121,2021-07-11,95,0,0,2010-07-30,2020-03-05,4.54,4.75,4.17,4.83,4.84,4.91,4.47,NaN,f,2,1,1,0,0.71

In [47]:
listings.shape

(8033, 74)

In [52]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8033 entries, 0 to 8032
Data columns (total 74 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            8033 non-null   int64
 1   listing_url                                   8033 non-null   object
 2   scrape_id                                     8033 non-null   int64
 3   last_scraped                                  8033 non-null   object
 4   name                                          8032 non-null   object
 5   description                                   7875 non-null   object
 6   neighborhood_overview                         5144 non-null   object
 7   picture_url                                   8033 non-null   object
 8   host_id                                       8033 non-null   int64
 9   host_url                                      8033 non-null   object
 10  host_name                                     7897 non-null   object
 11  host_since                                    7897 non-null   object
 12  host_location                                 7883 non-null   object
 13  host_about                                    4872 non-null   object
 14  host_response_time                            5391 non-null   object
 15  host_response_rate                            5391 non-null   object
 16  host_acceptance_rate                          5794 non-null   object
 17  host_is_superhost                             7897 non-null   object
 18  host_thumbnail_url                            7897 non-null   object
 19  host_picture_url                              7897 non-null   object
 20  host_neighbourhood                            7292 non-null   object
 21  host_listings_count                           7897 non-null   float64
 22  host_total_listings_count                     7897 non-null   float64
 23  host_verifications                            8033 non-null   object
 24  host_has_profile_pic                          7897 non-null   object
 25  host_identity_verified                        7897 non-null   object
 26  neighbourhood                                 5144 non-null   object
 27  neighbourhood_cleansed                        8033 non-null   object
 28  neighbourhood_group_cleansed                  0 non-null      float64
 29  latitude                                      8033 non-null   float64
 30  longitude                                     8033 non-null   float64
 31  property_type                                 8033 non-null   object
 32  room_type                                     8033 non-null   object
 33  accommodates                                  8033 non-null   int64
 34  bathrooms                                     0 non-null      float64
 35  bathrooms_text                                8024 non-null   object
 36  bedrooms                                      7188 non-null   float64
 37  beds                                          7736 non-null   float64
 38  amenities                                     8033 non-null   object
 39  price                                         8033 non-null   object
 40  minimum_nights                                8033 non-null   int64
 41  maximum_nights                                8033 non-null   int64
 42  minimum_minimum_nights                        8033 non-null   int64
 43  maximum_minimum_nights                        8033 non-null   int64
 44  minimum_maximum_nights                        8033 non-null   int64
 45  maximum_maximum_nights                        8033 non-null   int64
 46  minimum_nights_avg_ntm                        8033 non-null   float64
 47  maximum_nights_avg_ntm                        8033 non-null   float64
 48  calendar_updated                              0 non-null      float64
 49  has_availability                              8033 non-null   object
 50  availability_30                               8033 non-null   int64
 51  availability_60                               8033 non-null   int64
 52  availability_90                               8033 non-null   int64
 53  availability_365                              8033 non-null   int64
 54  calendar_last_scraped                         8033 non-null   object
 55  number_of_reviews                             8033 non-null   int64
 56  number_of_reviews_ltm                         8033 non-null   int64
 57  number_of_reviews_l30d                        8033 non-null   int64
 58  first_review                                  5826 non-null   object
 59  last_review                                   5826 non-null   object
 60  review_scores_rating                          5826 non-null   float64
 61  review_scores_accuracy                        5742 non-null   float64
 62  review_scores_cleanliness                     5743 non-null   float64
 63  review_scores_checkin                         5739 non-null   float64
 64  review_scores_communication                   5743 non-null   float64
 65  review_scores_location                        5740 non-null   float64
 66  review_scores_value                           5737 non-null   float64
 67  license                                       2 non-null      object
 68  instant_bookable                              8033 non-null   object
 69  calculated_host_listings_count                8033 non-null   int64
 70  calculated_host_listings_count_entire_homes   8033 non-null   int64
 71  calculated_host_listings_count_private_rooms  8033 non-null   int64
 72  calculated_host_listings_count_shared_rooms   8033 non-null   int64
 73  reviews_per_month                             5826 non-null   float64
dtypes: float64(19), int64(21), object(34)
memory usage: 4.5+ MB

Create list of dc neighborhoods to work with

In [54]:
listings['neighbourhood_cleansed'].value_counts()

Capitol Hill, Lincoln Park                                                                           746
Union Station, Stanton Park, Kingman Park                                                            724
Columbia Heights, Mt. Pleasant, Pleasant Plains, Park View                                           687
Dupont Circle, Connecticut Avenue/K Street                                                           649
Shaw, Logan Circle                                                                                   548
Edgewood, Bloomingdale, Truxton Circle, Eckington                                                    531
Brightwood Park, Crestwood, Petworth                                                                 416
Downtown, Chinatown, Penn Quarters, Mount Vernon Square, North Capitol Street                        386
Kalorama Heights, Adams Morgan, Lanier Heights                                                       347
West End, Foggy Bottom, GWU                                                                          302
Howard University, Le Droit Park, Cardozo/Shaw                                                       289
Southwest Employment Area, Southwest/Waterfront, Fort McNair, Buzzard Point                          288
Georgetown, Burleith/Hillandale                                                                      232
Ivy City, Arboretum, Trinidad, Carver Langston                                                       215
Takoma, Brightwood, Manor Park                                                                       173
Brookland, Brentwood, Langdon                                                                        119
Lamont Riggs, Queens Chapel, Fort Totten, Pleasant Hill                                              116
Congress Heights, Bellevue, Washington Highlands                                                      99
Cathedral Heights, McLean Gardens, Glover Park                                                        95
Cleveland Park, Woodley Park, Massachusetts Avenue Heights, Woodland-Normanstone Terrace              89
Twining, Fairlawn, Randle Highlands, Penn Branch, Fort Davis Park, Fort Dupont                        88
Capitol View, Marshall Heights, Benning Heights                                                       82
North Michigan Park, Michigan Park, University Heights                                                80
Spring Valley, Palisades, Wesley Heights, Foxhall Crescent, Foxhall Village, Georgetown Reservoir     80
Friendship Heights, American University Park, Tenleytown                                              77
Near Southeast, Navy Yard                                                                             69
Historic Anacostia                                                                                    65
Hawthorne, Barnaby Woods, Chevy Chase                                                                 52
North Cleveland Park, Forest Hills, Van Ness                                                          51
Deanwood, Burrville, Grant Park, Lincoln Heights, Fairmont Heights                                    50
Woodridge, Fort Lincoln, Gateway                                                                      50
River Terrace, Benning, Greenway, Dupont Park                                                         46
Mayfair, Hillbrook, Mahaning Heights                                                                  44
Colonial Village, Shepherd Park, North Portal Estates                                                 40
Sheridan, Barry Farm, Buena Vista                                                                     33
Douglas, Shipley Terrace                                                                              28
Fairfax Village, Naylor Gardens, Hillcrest, Summit Park                                               24
Eastland Gardens, Kenilworth                                                                          15
Woodland/Fort Stanton, Garfield Heights, Knox Hill                                                     8
Name: neighbourhood_cleansed, dtype: int64

In [55]:
list_neighborhoods = np.unique(listings['neighbourhood_cleansed'])
list_neighborhoods

array(['Brightwood Park, Crestwood, Petworth',
       'Brookland, Brentwood, Langdon', 'Capitol Hill, Lincoln Park',
       'Capitol View, Marshall Heights, Benning Heights',
       'Cathedral Heights, McLean Gardens, Glover Park',
       'Cleveland Park, Woodley Park, Massachusetts Avenue Heights, Woodland-Normanstone Terrace',
       'Colonial Village, Shepherd Park, North Portal Estates',
       'Columbia Heights, Mt. Pleasant, Pleasant Plains, Park View',
       'Congress Heights, Bellevue, Washington Highlands',
       'Deanwood, Burrville, Grant Park, Lincoln Heights, Fairmont Heights',
       'Douglas, Shipley Terrace',
       'Downtown, Chinatown, Penn Quarters, Mount Vernon Square, North Capitol Street',
       'Dupont Circle, Connecticut Avenue/K Street',
       'Eastland Gardens, Kenilworth',
       'Edgewood, Bloomingdale, Truxton Circle, Eckington',
       'Fairfax Village, Naylor Gardens, Hillcrest, Summit Park',
       'Friendship Heights, American University Park, Tenleytown',
       'Georgetown, Burleith/Hillandale',
       'Hawthorne, Barnaby Woods, Chevy Chase', 'Historic Anacostia',
       'Howard University, Le Droit Park, Cardozo/Shaw',
       'Ivy City, Arboretum, Trinidad, Carver Langston',
       'Kalorama Heights, Adams Morgan, Lanier Heights',
       'Lamont Riggs, Queens Chapel, Fort Totten, Pleasant Hill',
       'Mayfair, Hillbrook, Mahaning Heights',
       'Near Southeast, Navy Yard',
       'North Cleveland Park, Forest Hills, Van Ness',
       'North Michigan Park, Michigan Park, University Heights',
       'River Terrace, Benning, Greenway, Dupont Park',
       'Shaw, Logan Circle', 'Sheridan, Barry Farm, Buena Vista',
       'Southwest Employment Area, Southwest/Waterfront, Fort McNair, Buzzard Point',
       'Spring Valley, Palisades, Wesley Heights, Foxhall Crescent, Foxhall Village, Georgetown Reservoir',
       'Takoma, Brightwood, Manor Park',
       'Twining, Fairlawn, Randle Highlands, Penn Branch, Fort Davis Park, Fort Dupont',
       'Union Station, Stanton Park, Kingman Park',
       'West End, Foggy Bottom, GWU',
       'Woodland/Fort Stanton, Garfield Heights, Knox Hill',
       'Woodridge, Fort Lincoln, Gateway'], dtype=object)

Create a locations dataframe and group by neighborhood. Find the average latitude and longitude for each neighborhood to serve as a center point of the neighborhoods for foursquare lookups.

In [56]:
locations = pd.concat([ listings[['neighbourhood_cleansed']] , listings[['latitude']] , listings[['longitude']]], axis=1)

In [57]:
locations.head()

                              neighbourhood_cleansed  latitude  longitude
0                                 Historic Anacostia  38.86339  -76.98889
1  Edgewood, Bloomingdale, Truxton Circle, Eckington  38.91195  -77.00456
2                       Eastland Gardens, Kenilworth  38.90585  -76.94469
3     Ivy City, Arboretum, Trinidad, Carver Langston  38.91217  -76.99249
4     Kalorama Heights, Adams Morgan, Lanier Heights  38.91887  -77.04008

In [58]:
locations = locations.groupby('neighbourhood_cleansed').mean()
locations

                                                     latitude  longitude
neighbourhood_cleansed
Brightwood Park, Crestwood, Petworth                38.946504 -77.024729
Brookland, Brentwood, Langdon                       38.926110 -76.983434
Capitol Hill, Lincoln Park                          38.884692 -76.992667
Capitol View, Marshall Heights, Benning Heights     38.885287 -76.931463
Cathedral Heights, McLean Gardens, Glover Park      38.924179 -77.075507
Cleveland Park, Woodley Park, Massachusetts Ave...  38.931255 -77.059736
Colonial Village, Shepherd Park, North Portal E...  38.986958 -77.035842
Columbia Heights, Mt. Pleasant, Pleasant Plains...  38.929396 -77.031084
Congress Heights, Bellevue, Washington Highlands    38.835467 -76.999961
Deanwood, Burrville, Grant Park, Lincoln Height...  38.900688 -76.928999
Douglas, Shipley Terrace                            38.846501 -76.978674
Downtown, Chinatown, Penn Quarters, Mount Verno...  38.901770 -77.022647
Dupont Circle, Connecticut Avenue/K Street          38.911625 -77.041218
Eastland Gardens, Kenilworth                        38.907531 -76.942734
Edgewood, Bloomingdale, Truxton Circle, Eckington   38.916464 -77.008268
Fairfax Village, Naylor Gardens, Hillcrest, Sum...  38.862713 -76.962163
Friendship Heights, American University Park, T...  38.950125 -77.082828
Georgetown, Burleith/Hillandale                     38.909281 -77.063361
Hawthorne, Barnaby Woods, Chevy Chase               38.965850 -77.066797
Historic Anacostia                                  38.863293 -76.984760
Howard University, Le Droit Park, Cardozo/Shaw      38.916935 -77.024726
Ivy City, Arboretum, Trinidad, Carver Langston      38.905316 -76.984594
Kalorama Heights, Adams Morgan, Lanier Heights      38.920034 -77.043688
Lamont Riggs, Queens Chapel, Fort Totten, Pleas...  38.956251 -77.003764
Mayfair, Hillbrook, Mahaning Heights                38.898830 -76.946792
Near Southeast, Navy Yard                           38.877511 -77.002252
North Cleveland Park, Forest Hills, Van Ness        38.947712 -77.064139
North Michigan Park, Michigan Park, University ...  38.944042 -76.990442
River Terrace, Benning, Greenway, Dupont Park       38.887868 -76.950891
Shaw, Logan Circle                                  38.909681 -77.025922
Sheridan, Barry Farm, Buena Vista                   38.858117 -76.988885
Southwest Employment Area, Southwest/Waterfront...  38.872262 -77.013675
Spring Valley, Palisades, Wesley Heights, Foxha...  38.917953 -77.091076
Takoma, Brightwood, Manor Park                      38.966057 -77.020223
Twining, Fairlawn, Randle Highlands, Penn Branc...  38.870024 -76.971422
Union Station, Stanton Park, Kingman Park           38.898062 -76.993880
West End, Foggy Bottom, GWU                         38.902264 -77.051305
Woodland/Fort Stanton, Garfield Heights, Knox Hill  38.853525 -76.968769
Woodridge, Fort Lincoln, Gateway                    38.930495 -76.966197

In [59]:
locations.reset_index(inplace=True)

In [60]:
locations

                               neighbourhood_cleansed   latitude  longitude
0                Brightwood Park, Crestwood, Petworth  38.946504 -77.024729
1                       Brookland, Brentwood, Langdon  38.926110 -76.983434
2                          Capitol Hill, Lincoln Park  38.884692 -76.992667
3     Capitol View, Marshall Heights, Benning Heights  38.885287 -76.931463
4      Cathedral Heights, McLean Gardens, Glover Park  38.924179 -77.075507
5   Cleveland Park, Woodley Park, Massachusetts Av...  38.931255 -77.059736
6   Colonial Village, Shepherd Park, North Portal ...  38.986958 -77.035842
7   Columbia Heights, Mt. Pleasant, Pleasant Plain...  38.929396 -77.031084
8    Congress Heights, Bellevue, Washington Highlands  38.835467 -76.999961
9   Deanwood, Burrville, Grant Park, Lincoln Heigh...  38.900688 -76.928999
10                           Douglas, Shipley Terrace  38.846501 -76.978674
11  Downtown, Chinatown, Penn Quarters, Mount Vern...  38.901770 -77.022647
12         Dupont Circle, Connecticut Avenue/K Street  38.911625 -77.041218
13                       Eastland Gardens, Kenilworth  38.907531 -76.942734
14  Edgewood, Bloomingdale, Truxton Circle, Eckington  38.916464 -77.008268
15  Fairfax Village, Naylor Gardens, Hillcrest, Su...  38.862713 -76.962163
16  Friendship Heights, American University Park, ...  38.950125 -77.082828
17                    Georgetown, Burleith/Hillandale  38.909281 -77.063361
18              Hawthorne, Barnaby Woods, Chevy Chase  38.965850 -77.066797
19                                 Historic Anacostia  38.863293 -76.984760
20     Howard University, Le Droit Park, Cardozo/Shaw  38.916935 -77.024726
21     Ivy City, Arboretum, Trinidad, Carver Langston  38.905316 -76.984594
22     Kalorama Heights, Adams Morgan, Lanier Heights  38.920034 -77.043688
23  Lamont Riggs, Queens Chapel, Fort Totten, Plea...  38.956251 -77.003764
24               Mayfair, Hillbrook, Mahaning Heights  38.898830 -76.946792
25                          Near Southeast, Navy Yard  38.877511 -77.002252
26       North Cleveland Park, Forest Hills, Van Ness  38.947712 -77.064139
27  North Michigan Park, Michigan Park, University...  38.944042 -76.990442
28      River Terrace, Benning, Greenway, Dupont Park  38.887868 -76.950891
29                                 Shaw, Logan Circle  38.909681 -77.025922
30                  Sheridan, Barry Farm, Buena Vista  38.858117 -76.988885
31  Southwest Employment Area, Southwest/Waterfron...  38.872262 -77.013675
32  Spring Valley, Palisades, Wesley Heights, Foxh...  38.917953 -77.091076
33                     Takoma, Brightwood, Manor Park  38.966057 -77.020223
34  Twining, Fairlawn, Randle Highlands, Penn Bran...  38.870024 -76.971422
35          Union Station, Stanton Park, Kingman Park  38.898062 -76.993880
36                        West End, Foggy Bottom, GWU  38.902264 -77.051305
37  Woodland/Fort Stanton, Garfield Heights, Knox ...  38.853525 -76.968769
38                   Woodridge, Fort Lincoln, Gateway  38.930495 -76.966197

Get list of average latitude and longitude coordinates by neighborhood for next steps with foursquare lookups.

In [61]:
lat_lon = list(zip(locations['latitude'], locations['longitude']))
lat_lon = [str(lat_lon[i]).replace('(','').replace(')','') for i in range(0,len(lat_lon))]

In [74]:
lat_lon[0]

'38.946504018489904, -77.02472855730106'

Create dictionary of venue categories to loop through for each neighborhood

In [63]:
category_dict = {
    'historic site': '4deefb944765f83613cdba6e',
    'museum': '4bf58dd8d48988d181941735',
    'metro': '4bf58dd8d48988d1fd931735',
    'music venue': '4bf58dd8d48988d1e5931735',
    'perfomring arts venue': '4bf58dd8d48988d1f2931735',
    'college and university': '4d4b7105d754a06372d81259',
    'food': '4d4b7105d754a06374d81259',
    'nightlife spot': '4d4b7105d754a06376d81259',
    'outdoors and recreation': '4d4b7105d754a06377d81259',
    'government building': '4bf58dd8d48988d126941735',
    'clothing store': '4bf58dd8d48988d103951735'
                }

In [64]:
cat_list = [value for key, value in category_dict.items() ]
cat_list

['4deefb944765f83613cdba6e',
 '4bf58dd8d48988d181941735',
 '4bf58dd8d48988d1fd931735',
 '4bf58dd8d48988d1e5931735',
 '4bf58dd8d48988d1f2931735',
 '4d4b7105d754a06372d81259',
 '4d4b7105d754a06374d81259',
 '4d4b7105d754a06376d81259',
 '4d4b7105d754a06377d81259',
 '4bf58dd8d48988d126941735',
 '4bf58dd8d48988d103951735']

In [65]:
cat_key_list = [key for key, value in category_dict.items() ]
cat_key_list

['historic site',
 'museum',
 'metro',
 'music venue',
 'perfomring arts venue',
 'college and university',
 'food',
 'nightlife spot',
 'outdoors and recreation',
 'government building',
 'clothing store']

Set up Foursquare API pull on neighborhood venues

In [84]:
#set up first pull

venue_list = []

for j in cat_list:

    url = 'https://api.foursquare.com/v2/venues/search'

    params = dict(
    client_id='JWWPNW4JVAJ4OLM3ZSWASPF0R2ZP4DVHKQ52FGRLK0514J3Q',
    client_secret='NL0E1FVEIB0I1N22M51IRHPVUW45WDG0RSFF4IPW5Z01HBXM',
    v='20180323',
    ll= lat_lon[0],
    categoryId = j,
    limit=50,
    radius=1000
    #.6 mile radius
    )

    #make request
    req = requests.get(url=url, params=params)

    #pull necessary data
    data = json.loads(req.text)

    x = len(data['response']['venues'])
    
    venue_list.append(x)
    
full = pd.DataFrame(venue_list).T

full.columns = cat_key_list

In [85]:
full

,historic site,museum,metro,music venue,perfomring arts venue,college and university,food,nightlife spot,outdoors and recreation,government building,clothing store
0,1,1,1,3,5,8,48,15,47,10,10

In [86]:
#set up pulls for the rest of the neighborhoods

for i in lat_lon[1:]:

    venue_list = []
    
    for j in cat_list:

        #set up url for looping
        url = 'https://api.foursquare.com/v2/venues/search'

        params = dict(
        client_id='JWWPNW4JVAJ4OLM3ZSWASPF0R2ZP4DVHKQ52FGRLK0514J3Q',
        client_secret='NL0E1FVEIB0I1N22M51IRHPVUW45WDG0RSFF4IPW5Z01HBXM',
        v='20180323',
        ll= i,
        categoryId = j,
        limit=50,
        radius=1000
        #.6 mile radius
        )

        #make request
        req = requests.get(url=url, params=params)

        #pull necessary data
        data = json.loads(req.text)

        x = len(data['response']['venues'])

        venue_list.append(x)

    temp = pd.DataFrame(venue_list).T

    temp.columns = cat_key_list

    full = pd.concat([full, temp])

In [87]:
full.reset_index(inplace=True)

In [88]:
full

,index,historic site,museum,metro,music venue,perfomring arts venue,college and university,food,nightlife spot,outdoors and recreation,government building,clothing store
0,0,1,1,1,3,5,8,48,15,47,10,10
1,0,0,0,0,2,6,6,44,22,29,10,8
2,0,8,6,2,0,9,13,50,49,46,49,23
3,0,1,0,1,0,0,4,13,1,15,4,0
4,0,5,0,0,1,4,17,48,27,44,24,2
5,0,7,0,2,3,4,10,50,19,46,23,7
6,0,7,3,1,4,3,16,50,19,44,33,7
7,0,7,2,3,22,23,50,50,50,46,39,29
8,0,1,0,0,1,1,8,18,1,17,9,2
9,0,1,0,1,0,0,1,13,2,12,1,0
10,0,4,0,2,0,2,2,15,2,17,3,3
11,0,42,48,8,16,37,42,50,50,48,50,49
12,0,36,28,2,15,46,44,50,50,45,48,47
13,0,1,0,2,0,1,1,9,1,18,2,0
14,0,2,2,0,7,12,50,50,45,44,31,13
15,0,0,0,0,0,0,2,22,1,15,11,5
16,0,3,0,2,2,12,49,49,12,45,9,24
17,0,9,6,0,5,11,50,50,50,48,48,50
18,0,2,0,0,1,1,2,24,4,21,2,6
19,0,1,2,1,0,3,10,25,5,28,21,5
20,0,18,10,2,23,37,49,50,50,46,36,46
21,0,1,2,0,3,16,48,50,49,44,14,19
22,0,27,16,2,16,22,47,50,50,47,50,45
23,0,2,0,1,0,3,7,28,7,26,7,1
24,0,0,0,2,0,2,3,25,0,13,3,4
25,0,10,2,3,2,8,5,50,50,47,48,24
26,0,5,4,1,2,8,48,45,5,44,35,1
27,0,1,0,0,0,4,48,34,7,33,6,3
28,0,0,0,0,0,1,4,19,0,17,2,4
29,0,31,28,5,24,38,46,50,50,44,47,48
30,0,0,2,1,0,3,10,28,5,23,23,5
31,0,6,1,2,5,7,11,50,50,46,48,5
32,0,2,1,0,0,1,40,18,4,29,6,0
33,0,6,1,1,4,10,8,50,13,39,5,2
34,0,0,0,0,0,0,3,26,1,22,8,3
35,0,4,5,3,4,20,47,50,48,46,50,34
36,0,22,17,3,12,39,50,50,50,44,49,49
37,0,1,2,1,0,0,3,20,1,24,8,3
38,0,0,0,0,0,3,4,35,10,30,5,4

Combine neighborhood locations df with venue information

In [89]:
neighborhood_venues = pd.concat([locations, full], axis=1)

In [90]:
neighborhood_venues

,neighbourhood_cleansed,latitude,longitude,index,historic site,museum,metro,music venue,perfomring arts venue,college and university,food,nightlife spot,outdoors and recreation,government building,clothing store
0,"Brightwood Park, Crestwood, Petworth",38.946504,-77.024729,0,1,1,1,3,5,8,48,15,47,10,10
1,"Brookland, Brentwood, Langdon",38.926110,-76.983434,0,0,0,0,2,6,6,44,22,29,10,8
2,"Capitol Hill, Lincoln Park",38.884692,-76.992667,0,8,6,2,0,9,13,50,49,46,49,23
3,"Capitol View, Marshall Heights, Benning Heights",38.885287,-76.931463,0,1,0,1,0,0,4,13,1,15,4,0
4,"Cathedral Heights, McLean Gardens, Glover Park",38.924179,-77.075507,0,5,0,0,1,4,17,48,27,44,24,2
5,"Cleveland Park, Woodley Park, Massachusetts Av...",38.931255,-77.059736,0,7,0,2,3,4,10,50,19,46,23,7
6,"Colonial Village, Shepherd Park, North Portal ...",38.986958,-77.035842,0,7,3,1,4,3,16,50,19,44,33,7
7,"Columbia Heights, Mt. Pleasant, Pleasant Plain...",38.929396,-77.031084,0,7,2,3,22,23,50,50,50,46,39,29
8,"Congress Heights, Bellevue, Washington Highlands",38.835467,-76.999961,0,1,0,0,1,1,8,18,1,17,9,2
9,"Deanwood, Burrville, Grant Park, Lincoln Heigh...",38.900688,-76.928999,0,1,0,1,0,0,1,13,2,12,1,0
10,"Douglas, Shipley Terrace",38.846501,-76.978674,0,4,0,2,0,2,2,15,2,17,3,3
11,"Downtown, Chinatown, Penn Quarters, Mount Vern...",38.901770,-77.022647,0,42,48,8,16,37,42,50,50,48,50,49
12,"Dupont Circle, Connecticut Avenue/K Street",38.911625,-77.041218,0,36,28,2,15,46,44,50,50,45,48,47
13,"Eastland Gardens, Kenilworth",38.907531,-76.942734,0,1,0,2,0,1,1,9,1,18,2,0
14,"Edgewood, Bloomingdale, Truxton Circle, Eckington",38.916464,-77.008268,0,2,2,0,7,12,50,50,45,44,31,13
15,"Fairfax Village, Naylor Gardens, Hillcrest, Su...",38.862713,-76.962163,0,0,0,0,0,0,2,22,1,15,11,5
16,"Friendship Heights, American University Park, ...",38.950125,-77.082828,0,3,0,2,2,12,49,49,12,45,9,24
17,"Georgetown, Burleith/Hillandale",38.909281,-77.063361,0,9,6,0,5,11,50,50,50,48,48,50
18,"Hawthorne, Barnaby Woods, Chevy Chase",38.965850,-77.066797,0,2,0,0,1,1,2,24,4,21,2,6
19,Historic Anacostia,38.863293,-76.984760,0,1,2,1,0,3,10,25,5,28,21,5
20,"Howard University, Le Droit Park, Cardozo/Shaw",38.916935,-77.024726,0,18,10,2,23,37,49,50,50,46,36,46
21,"Ivy City, Arboretum, Trinidad, Carver Langston",38.905316,-76.984594,0,1,2,0,3,16,48,50,49,44,14,19
22,"Kalorama Heights, Adams Morgan, Lanier Heights",38.920034,-77.043688,0,27,16,2,16,22,47,50,50,47,50,45
23,"Lamont Riggs, Queens Chapel, Fort Totten, Plea...",38.956251,-77.003764,0,2,0,1,0,3,7,28,7,26,7,1
24,"Mayfair, Hillbrook, Mahaning Heights",38.898830,-76.946792,0,0,0,2,0,2,3,25,0,13,3,4
25,"Near Southeast, Navy Yard",38.877511,-77.002252,0,10,2,3,2,8,5,50,50,47,48,24
26,"North Cleveland Park, Forest Hills, Van Ness",38.947712,-77.064139,0,5,4,1,2,8,48,45,5,44,35,1
27,"North Michigan Park, Michigan Park, University...",38.944042,-76.990442,0,1,0,0,0,4,48,34,7,33,6,3
28,"River Terrace, Benning, Greenway, Dupont Park",38.887868,-76.950891,0,0,0,0,0,1,4,19,0,17,2,4
29,"Shaw, Logan Circle",38.909681,-77.025922,0,31,28,5,24,38,46,50,50,44,47,48
30,"Sheridan, Barry Farm, Buena Vista",38.858117,-76.988885,0,0,2,1,0,3,10,28,5,23,23,5
31,"Southwest Employment Area, Southwest/Waterfron...",38.872262,-77.013675,0,6,1,2,5,7,11,50,50,46,48,5
32,"Spring Valley, Palisades, Wesley Heights, Foxh...",38.917953,-77.091076,0,2,1,0,0,1,40,18,4,29,6,0
33,"Takoma, Brightwood, Manor Park",38.966057,-77.020223,0,6,1,1,4,10,8,50,13,39,5,2
34,"Twining, Fairlawn, Randle Highlands, Penn Bran...",38.870024,-76.971422,0,0,0,0,0,0,3,26,1,22,8,3
35,"Union Station, Stanton Park, Kingman Park",38.898062,-76.993880,0,4,5,3,4,20,47,50,48,46,50,34
36,"West End, Foggy Bottom, GWU",38.902264,-77.051305,0,22,17,3,12,39,50,50,50,44,49,49
37,"Woodland/Fort Stanton, Garfield Heights, Knox ...",38.853525,-76.968769,0,1,2,1,0,0,3,20,1,24,8,3
38,"Woodridge, Fort Lincoln, Gateway",38.930495,-76.966197,0,0,0,0,0,3,4,35,10,30,5,4

In [91]:
neighborhood_venues.drop(columns=['index'], inplace=True)

Export neighborhood venue information to csv

In [92]:
neighborhood_venues.to_csv('../data/neighborhood_venues.csv')